name: Clip coupons

on:
  push:
  schedule:
    - cron: "0 16 * * *"

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  app:
    name: Safeway Coupons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Safeway credentials
        run: |
          echo "SAFEWAY_ACCOUNT_USERNAME=${{ secrets.SAFEWAY_ACCOUNT_USERNAME }}" >> ${GITHUB_ENV}
          echo "SAFEWAY_ACCOUNT_PASSWORD=${{ secrets.SAFEWAY_ACCOUNT_PASSWORD }}" >> ${GITHUB_ENV}

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget gnupg tini
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo tee /usr/share/keyrings/chrome.pub
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/chrome.pub] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update -y
          sudo apt install -y google-chrome-stable sendmail
          python3 -m pip install --upgrade pip
          pip install safeway-coupons setuptools
          # TODO: Remove when this PR is merged: https://github.com/smkent/safeway-coupons/pull/134
          test /opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/safeway_coupons/session.py
          cp patch/session.py /opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/safeway_coupons/session.py


      - name: Clip coupons
        run: |
          safeway-coupons
      
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
